TARGET 	= test

CC 		= gcc
CXX 	= g++

INCLUDES= -I../
CFLAGS 	= -g -Wall $(INCLUDES)
CXXFLAGS= -g -Wall $(INCLUDES)

LDFLAGS = -g -L../
LDLIBS 	= -lbigint

$(TARGET):

clean:
	rm -f a.out *.o $(TARGET)
