#!/bin/bash

# for my alt C solution
# later put in regex stuff altering makefile

[ -e compare-alt.txt ] && rm compare-alt.txt

printf "This is the alt C solution time:\n" >> compare-alt.txt
(time ./runplz-alt) 2>> compare-alt.txt

