#!/bin/bash

# A bash script for comparing the runtime of
# various solutions in different languages

[ -e compare.txt ] && rm compare.txt

# C solution, includes compile, execution,
# and cleanup
printf "This is the C solutions time:\n" >> compare.txt
(time ./runplz) 2>> compare.txt

# Python solution, pipe output to same text file
#printf "\nThis is the Python solutions time:\n" >> compare.txt
#cd vers_py && (time ./runplz) 2>> ../compare.txt && cd ..

# fuck it, let's time Java as well
printf "\nThis is the Java solutions time:\n" >> compare.txt
cd vers_java && (time ./runplz) 2>> ../compare.txt && cd ..

# Aaand let's have C++ as well while we're at it.
#printf "\nThis is the C++ solutions time:\n" >> compare.txt
#cd vers_cpp && (time ./runplz) 2>> ../compare.txt && cd ..
