TARGET	 = p17

CC 		 = gcc
CXX		 = g++

INCLUDES =
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES) -std=c++11

LDFLAGS  =
LDLIBS   =

$(TARGET):

.PHONY: clean
clean:
	rm -f a.out *.o $(TARGET)
