TARGET	= p16-compare

CC 		= gcc
CXX     = g++

INCLUDES=
CFLAGS  = -g -Wall $(INCLUDES)
CXXFLAGS= -g -Wall $(INCLUDES)

LDFLAGS = -g
LDLIBS  = -lpthread

$(TARGET):

clean:
	rm -f a.out *o $(TARGET)
