TARGET	= p16

CC 		= gcc
CXX		= g++

INCLUDES= -I../../libs 
CFLAGS  = -g -Wall $(INCLUDES)
CXXFLAGS= -g -Wall $(INCLUDES)

LDFLAGS = -g -L../../libs
LDLIBS  = -lbigint

$(TARGET):

clean:
	rm -f a.out *.o $(TARGET)
