#!/bin/bash

# a Simple Bash Script to run my solution

# Need to check if libary is made
if [ ! -e ../../libs/libbigint.a ]
then
        cd ../../libs && make && cd ../problem16/vers_cpp
fi

make && ./p16 1000 && make clean
