TARGET   = p7

CC 		 = gcc
CXX 	 = g++

INCLUDES =
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS  = -g
LDLIBS 	 = 

$(TARGET):

.PHONY: clean
clean:
	rm -f a.out *.o $(TARGET)
